frontend:
  servers:
    - "http://localhost:5173"
    - "http://k11c206.p.ssafy.io:3000"

spring:
  application:
    name: SCG
  jwt:
    secret: ${SPRING_JWT_SECRET:SSSSSAAANGGGGGGGMMMMMMIIIIIINNNN}
  cloud:
    gateway:
      routes:
        - id: user-test
          uri: http://user-spring-boot-service:8081 # User 서버 주소
          predicates:
            - Path=/api/v1/users/test
          filters:
            - name: JwtAuthFilter

        - id: user
          uri: http://user-spring-boot-service:8081
          predicates:
            - Path=/api/v1/users/**

        - id: kubetest
          uri: http://kubetest:9190
          predicates:
            - Path=/test
server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: debug

management:
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, gateway